name: Trigger Deploy Script
on:
  push:
     branches:
       - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Run deploy script
        uses: HydPy/hydpyconf2019@ci-cd
        shell: bash
        with:
          command: |
            source /root/.bashrc
            /root/deploy.py 2019
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
